const SEARCH_RES = "SEARCH_RES";
const SEARCH_ERROR = "SEARCH_ERROR";
const SEARCH_LOAD = "SEARCH_LOAD";
const GET_POP = "POPULAR";
const GET_GENRE = "GET_GENRE";

export {SEARCH_RES, SEARCH_ERROR, SEARCH_LOAD, GET_POP, GET_GENRE}